### PR TITLE
Update notebooks/index.ipynb

### PR DESCRIPTION
**Pull request by ekalosak**
*Description of changes:*

- added two unlisted tutorial jupyter notebooks to the index.ipynb
- added clarifying language to each tutorial subsection in the index.ipynb
- merged the 'Do it yourself' section into the 'Features' section because it was not clear what is the difference between the two

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by apaleyes** [comment]
This files needs updating: https://github.com/EmuKit/emukit/blob/master/integration_tests/emukit/notebooks/test_notebooks.py

Two reasons:
 - as it says, the said notebook takes too long to run, even for integ tests
 - it also allows us not to drag TF as a dependency

**Review by apaleyes — COMMENTED** [review]
This files needs updating: https://github.com/EmuKit/emukit/blob/master/integration_tests/emukit/notebooks/test_notebooks.py

Two reasons:
- as it says, the said notebook takes too long to run, even for integ tests
- it also allows us not to drag TF as a dependency

**Comment by ekalosak** [comment]
It's embarrassing how long these little things take to get to... But ok @apaleyes I updated the list of notebooks to skip so the NN tutorial isn't run in CI.

**Comment by apaleyes** [comment]
This was blocked by numpy/pandas incompatibility, fixed in https://github.com/EmuKit/emukit/pull/346. Merging!

**Pull request merged**
