### PR TITLE
added __str__ and __repr__ to emukit/core/*parameter.py

### PR DESCRIPTION
**Pull request by ekalosak**
*Description of changes:*
Implemented `str` and `repr` magic methods for the Parameter class and XyzParameter subclasses.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by apaleyes** [comment]
Thanks, very useful update!

Two comments:
1. Can you add new lines between methods, please?
2. It isn't immediately clear to me wny str and repr display different information. What was your thinking behind that decision?

**Comment by ekalosak** [comment]
1. Newlines incoming
2. The intention behind repr() is to provide _developer-friendly output_ i.e. something a dev can copy and paste to recreate the object being represented. The intention behind str() is to provide _user-friendly output_ i.e. something a user can easily interpret.

**Comment by apaleyes** [comment]
No, haven't considered any formatters yet. But will now, thanks for asking!

Can you have a look at the build failure? Seems to be some confusion with multi-line f-string.

**Comment by ekalosak** [comment]
@apaleyes looks like my hubris in submitting a PR without associated unit tests was misplaced. I've added tests.

**Review by apaleyes — APPROVED** [review]

**Comment by apaleyes** [comment]
Yup, tests are always good to have! thanks, merging now

**Pull request merged**
