### PR TITLE
Changes to categorical variable handling

### PR DESCRIPTION
**Pull request by sennendoko**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by apaleyes** [comment]
It's great to have this PR separated out, thanks again for doing that. I think it warrants a separate discussion most of all other changes.

The way categorical variables are handled in Emukit isn't very convenient, I have to agree with that. But that's the design choice we made, to avoid internal conversions that were very tricky and prone to bugs part of GPyOpt (just head to GPyOpt repo and lookup zip/unzip shenanigans). Since multiple encodings are possible, it is hard to keep proper track of categorical variable dimensionality when it isn't encoded. And that was with one certain model framework!

So in Emukit we offload handling of encoding to the user. Another reason is that Emukit takes model as an input, and in all likelihood the user has already dealt with encoding purely for modelling needs.

This is documented in [this notebook](https://github.com/EmuKit/emukit/blob/main/notebooks/Emukit-tutorial-select-neural-net-hyperparameters.ipynb) and [this issue](https://github.com/EmuKit/emukit/issues/319). A somewhat related discussion can also be found in [this PR](https://github.com/EmuKit/emukit/pull/191).

All of that considered, I might be overestimating the severity of these problems, so we can have a discussion on that here.

**Comment by apaleyes** [comment]
So, given the previous comment, would you still like to pursue this change? If so, we would need to consider different design options and choose the most appripriate one. Also, there is a [notebook](https://github.com/EmuKit/emukit/blob/main/notebooks/Emukit-tutorial-select-neural-net-hyperparameters.ipynb) that may need updating if this change goes through.

Additionaly, would be interesting to hear the motivation behind this change.

**Comment by ndalchau** [comment]
Hi @apaleyes , we've just learned that most of the changes in this PR are redundant. We were working in an old fork, and had added some changes to enable categorial parameters to be used in contexts. However, it seems that got resolved a year ago in  #305. With the other PRs integrated, we are now in a position to switch to the latest emukit. So, we can almost certainly close this PR.

**Comment by apaleyes** [comment]
Perfect, thanks @ndalchau ! I am closing this PR, but being aware of the API's inconvenience I would be open to restart the conversation about these changes, if you feel the need again.

**Comment by ndalchau** [comment]
Hi @apaleyes,

After looking at the code again, it appears some changes are still needed to get categorical parameters working properly within contexts.  

The main problem is as follows. Suppose you have a space containing one continuous and one categorical parameter:
```python
space = ParameterSpace([
    ContinuousParameter('x', 0, 1), 
    CategoricalParameter('y', OneHotEncoding(['A', 'B']))
])
```

Then eventually we choose to optimize `x` subject to `y` taking a value `A`. Nice, we can use a `Context`. e.g.
```python
context = {'y', 'A'}
```

I believe this is the correct way to initialize a context, because a `Context` is a `Dict[str, Any]`. 

However, when we pass this `context` to any `AcquisitionOptimiserBase`, the `optimize` method calls `_validate_context_parameters` (also takes `Dict[str, Any]`), which calls `check_in_domain` on all context values. When the context parameter is a categorical parameter, this `check_in_domain` method is expected to receive a `np.ndarray`. But what is being passed is a `str` (and in fact, can be `Any`).

I suspect `CategoricalParameter.check_in_domain` is expected to check the encoded parameter values, but it is being called on non-encoded parameters. 

My view is that this requires `check_in_domain` to work on `Any`, and to look up the values in the encoding (the approach of this PR). The only alternative I can think of is to change `_validate_context_parameters` to pass the encoded values. However, this would require those values existing in the domain, so would require a `check_in_domain` method. Hence why the former approach is required.

The problem can be identified by adding the following test (e.g. in `test_gradient_acquisition_optimizer.py`):
```python
def test_gradient_acquisition_optimizer_categorical_context(simple_square_acquisition):
    space = ParameterSpace([ContinuousParameter('x', 0, 1), CategoricalParameter('y', OneHotEncoding(['A', 'B']))])
    context = {'y': 'A'}
    optimizer = GradientAcquisitionOptimizer(space)
    opt_x, opt_val = optimizer.optimize(simple_square_acquisition, context)
```

Maybe we can add this test in the current PR, along with the other changes?

Please let us know what you'd prefer us to do to enable contexts to include categorical parameters, while still enabling use of `AcquisitionOptimizerBase`.

**Comment by ndalchau** [comment]
Just noticed there are issues with categorical variables in contexts in issue #359.

**Comment by apaleyes** [comment]
Thanks @ndalchau , now I understand what the issue is, and it also helped to clarify what was the matter in #359 . `check_in_domain` handling anything as an input sounds good, but might be a trifle complicated to get right. I'll have to give this a little think, but will come back with a better opinion.

**Comment by ndalchau** [comment]
Thanks @apaleyes. I just thought of a simpler change.

Instead of assuming that the context_values are encoded values in `acquisition_optimizer.py`, we could do:
```python
if hasattr(param, 'encoding'):
    warn = context_value not in param.encoding.categories 
else: 
    warn = param.check_in_domain(context_value) is False
if warn:
    _log.warning(context_name + ' with value ' + str(context_value), ' is out of the domain')
else:
    _log.info('Parameter ' + context_name + ' fixed to ' + str(context_value))
```

**Comment by apaleyes** [comment]
This proposed functionality is a good thing, it seems reasonable to allow users to use `context = {'y': 'A'}`. Therefore we need to:
  1. Check that the category we've been given is valid. If it isn't, just ignore it. Last fix from @ndalchau seems to be doing that.
  2. Make sure ContextManager can handle incorrect category. Test suit for ContextManager isn't very convincing right now.
  3. Consider merging validation into ContextManager. I am not entirely sure why they are separated, tbh. There might be a good reason though.

This seems most non-intrusive way, because it means we can leave categorical variable design as it is.

@ndalchau @sennendoko would any of you be interested in modifing this PR, or opening a new one, with this change?

Side note: `Dict[str, any]` as it is now in code seems a mistake. Here `any` is a Python function, which it probably should be `typing.Any`. Would be nice to incorporate this little fix.

**Pull request closed without merging**
