### PR TITLE
Parallel objective evaluation tutorial

### PR DESCRIPTION
**Pull request by ekalosak**
*Issue*:
#255

*Description of changes*:
I've written a tutorial on how to run Bayesian optimization with a parallelized external evaluation of batched suggestions using Emukit & asyncio.

sample_plot_output

This PR is rebased on top of PR #337 to build on the updated `notebooks/index.ipynb` format introduced there.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by apaleyes** [comment]
That's amazing, thanks for doing this! You had a very productive break @ekalosak 

It seems that we have some issues with Travis at the moment. I think it's past time we moved to Github Actions anyway, so please hang in there while I am working on the transition. I promise to have a closer look at all the PRs once this is done, shouldn't take more than a few days.

**Comment by ekalosak** [comment]
@apaleyes no rush, please let me know if there's anything to fix here. Thanks for your efforts maintaining emukit 💪

**Comment by ekalosak** [comment]
Looks like the issue in the tests is
```
FAILED integration_tests/emukit/notebooks/test_notebooks.py::test_notebook_runs_without_errors[Emukit-tutorial-sensitivity-montecarlo.ipynb]
```
which has nothing to do with the present PR. Is this a known flaky test? Or a known testing issue?

**Comment by apaleyes** [comment]
@ekalosak i think this PR conflicts with your other PR #337 , which is now merged. Can you rebase and bring this one up to date please?

**Comment by ekalosak** [comment]
@apaleyes rebased 👍 ,

**Review by apaleyes — APPROVED** [review]
This is awesome contribution, thanks @ekalosak !

**Pull request merged**
